#!/usr/bin/env python3
"""Refresh data/flows.csv with spot-Bitcoin-ETF net flows.

This is intentionally source-agnostic: point it at any URL that returns daily
rows of `YYYY-MM-DD,net_flow` (USD millions). It aggregates to monthly net flow
and writes data/flows.csv in the format generate.py expects.

Free sources you can adapt (all need network access; they won't run in a no-egress sandbox):
  - Farside Investors BTC ETF flow table   https://farside.co.uk/btc/
  - SoSoValue / public Google-Sheet CSV exports
  - Your own maintained CSV in the repo

Usage:
  FLOWS_URL="https://example.com/btc-etf-daily.csv" python3 fetch_flows.py
  python3 fetch_flows.py https://example.com/btc-etf-daily.csv

If no URL is given it leaves the existing seed values untouched and exits 0,
so CI stays green even before a source is wired up.
"""
import csv, io, os, sys, urllib.request
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "data", "flows.csv")

def main():
    url = sys.argv[1] if len(sys.argv) > 1 else os.environ.get("FLOWS_URL")
    if not url:
        print("No FLOWS_URL set; keeping existing data/flows.csv seed values.")
        return 0

    print(f"Fetching {url} ...")
    with urllib.request.urlopen(url, timeout=30) as r:
        text = r.read().decode("utf-8", "replace")

    monthly = defaultdict(float)
    for row in csv.reader(io.StringIO(text)):
        if len(row) < 2:
            continue
        date, val = row[0].strip(), row[1].strip()
        if len(date) < 7 or not date[:4].isdigit():
            continue  # skip headers / blanks
        try:
            monthly[date[:7]] += float(val.replace(",", ""))
        except ValueError:
            continue

    if not monthly:
        print("No parseable rows; not overwriting flows.csv.", file=sys.stderr)
        return 1

    with open(OUT, "w", newline="") as f:
        f.write("# US spot Bitcoin ETF monthly NET flow, USD millions (+ = institutional buying).\n")
        f.write(f"# Auto-generated by fetch_flows.py from {url}\n")
        w = csv.writer(f)
        w.writerow(["date", "net_flow_musd"])
        for ym in sorted(monthly):
            w.writerow([ym, round(monthly[ym], 1)])
    print(f"Wrote {len(monthly)} months to {OUT}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
